# Generated by Django 4.1 on 2022-08-29 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=140)),
                ('marca', models.CharField(max_length=140)),
                ('categoria', models.CharField(choices=[('1', 'Processadores'), ('2', 'RAM'), ('3', 'Placas-Mãe'), ('4', 'Air Cooler'), ('5', 'Water Cooler'), ('6', 'Periféricos')], max_length=140)),
                ('qtd', models.IntegerField()),
                ('preço', models.FloatField()),
                ('prod_img', models.ImageField(null=True, upload_to='loja/static/loja/images', verbose_name='Product Image')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('produtos_nome', models.CharField(max_length=255, null=True)),
                ('qtd', models.IntegerField(default=1)),
                ('prod_img', models.CharField(max_length=255)),
                ('preço', models.FloatField()),
                ('produtos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
