# Generated by Django 4.1 on 2022-08-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=140)),
                ('marca', models.CharField(max_length=140)),
                ('qtd', models.IntegerField()),
                ('preço', models.FloatField()),
            ],
        ),
    ]
