# Generated by Django 4.1 on 2022-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('cat_img', models.ImageField(null=True, upload_to='loja/static/loja/images', verbose_name='Category image')),
            ],
        ),
    ]
