# Generated by Django 4.1 on 2022-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=140)),
                ('sobrenome', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
                ('telefone', models.CharField(max_length=140)),
                ('username', models.CharField(max_length=140)),
                ('password', models.CharField(max_length=140)),
            ],
        ),
    ]
