# Generated by Django 4.1 on 2022-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
