# Generated by Django 4.1 on 2022-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='static/loja/images', verbose_name='Product Image'),
        ),
    ]
