# Generated by Django 4.1 on 2022-08-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_alter_produto_prod_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='loja/static/loja/images', verbose_name='Product Image'),
        ),
    ]
