# Generated by Django 4.1 on 2022-08-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Processadores'), ('2', 'RAM'), ('3', 'Placas-Mãe'), ('4', 'Air Cooler'), ('5', 'Water Cooler')], default=0, max_length=140),
            preserve_default=False,
        ),
    ]
