# Generated by Django 4.1 on 2022-08-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_alter_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('produtos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.usuario')),
            ],
        ),
    ]
