# Generated by Django 4.1 on 2022-08-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='userid',
        ),
    ]
