# Generated by Django 4.1 on 2022-08-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_remove_cart_userid_cart_username_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prod_img',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='qtd',
            field=models.IntegerField(default=1),
        ),
    ]
