# Generated by Django 4.1 on 2022-08-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_cart_prod_img_alter_cart_qtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='preço',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
