# Generated by Django 4.1 on 2022-08-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
