# Generated by Django 4.1 on 2022-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='produtos_nome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
